### ISSUE TITLE
Sometimes `arraycopy: length -XXX is negative` is raised

### ISSUE THREAD

**Issue by Mingun** [coderazzi/tablefilter-swing#52]
Sometimes I get the following exception in my company's utility (length is varied):
```
java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -5774 is negative
	at java.base/java.lang.System.arraycopy(Native Method)
	at java.base/java.lang.AbstractStringBuilder.shift(AbstractStringBuilder.java:1085)
	at java.base/java.lang.AbstractStringBuilder.delete(AbstractStringBuilder.java:926)
	at java.base/java.lang.StringBuilder.delete(StringBuilder.java:283)
	at net.coderazzi.filters.parser.Parser.escape(Parser.java:191)
	at net.coderazzi.filters.gui.editor.EditorComponent$EditableTC.escapeChoice(EditorComponent.java:678)
	at net.coderazzi.filters.gui.editor.ChoicesListModel.addContent(ChoicesListModel.java:165)
	at net.coderazzi.filters.gui.editor.PopupComponent.addChoices(PopupComponent.java:123)
	at net.coderazzi.filters.gui.editor.FilterEditor.addChoices(FilterEditor.java:418)
	at net.coderazzi.filters.gui.editor.FilterEditor.setChoices(FilterEditor.java:408)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport$EditorHandle.iterationCompleted(AdaptiveChoicesHandler.java:650)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.extractChoices(AdaptiveChoicesHandler.java:444)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.rowsAdded(AdaptiveChoicesHandler.java:269)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler$AdaptiveChoicesSupport.<init>(AdaptiveChoicesHandler.java:227)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler.createAdaptiveChoicesSupport(AdaptiveChoicesHandler.java:146)
	at net.coderazzi.filters.gui.AdaptiveChoicesHandler.setInterrupted(AdaptiveChoicesHandler.java:79)
	at net.coderazzi.filters.gui.FiltersHandler.enableNotifications(FiltersHandler.java:447)
	at net.coderazzi.filters.gui.TableFilterHeader.setTable(TableFilterHeader.java:264)
	at net.coderazzi.filters.gui.TableFilterHeader.<init>(TableFilterHeader.java:209)
	at net.coderazzi.filters.gui.TableFilterHeader.<init>(TableFilterHeader.java:187)
	at org.radixware.kernel.utils.traceview.window.TablePanel.createTable(TablePanel.java:1009)
	at org.radixware.kernel.utils.traceview.window.TablePanel.createTablePanel(TablePanel.java:1043)
	at org.radixware.kernel.utils.traceview.window.TablePanel.run(TablePanel.java:414)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
Unfortunately, cannot say what exactly data causing this because this is trace viewer utility and bug is appeared on big files. Probably the bug is related to the **Message** column in our utility, where variance of data is very high.

The latest [5.5.4](https://github.com/coderazzi/tablefilter-swing/releases/tag/tablefilter-swing-5.5.4) release is used.

The code that initializes `TableFilterHeader`:
```java
JTable table = new JTable(new DataTraceModel(dataset.getEvents())) { ... });
final TableFilterHeader filter = new TableFilterHeader(table, AutoChoices.ENABLED);// TablePanel.java:1009
```

**Comment by coderazzi** [comment]
Hi, Mingun,
Looking at your stack trace, I can see that the problem starts on a
separate thread, is that the case?
Normally, all Swing operations should be handled by the UI thread, using
SwingUtilities' invokeLater or invokeAndWait, is it possible that there are
multiple threads in place, not correctly synchronized with the II thread??
Best,

 Lu.
